# site settings

title:          Michele Piazzai
tagline:        Carlos III University of Madrid
tagshort:       UC3M
url:            https://piazzai.github.io
baseurl:        ""
permalink:      pretty
repo:           https://github.com/piazzai/piazzai.github.io

# author settings

author:
  name:         Michele Piazzai
  email:        michele.piazzai@uc3m.es

# build settings

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - .git
  - .jekyll-cache
  - .sass-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - vendor

sass:
  sass_dir:     _sass
  sourcemap:    never

feed:
  path:         atom.xml

autopages:
  enabled:      false

pagination:
  enabled:      false
  per_page:     1
  sort_reverse: true
  permalink:    /:num/
  title:        ":title &middot; Page :num"
