title: 一片叶
description: 临时页面  # 描述
taglong: Hello Friend # 副标题
tagshort: 洗洗睡吧
url: https://yipianye.github.io
baseurl:  '/piazzai'
permalink: pretty
repo: https://github.com/

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never
