title: Michele Piazzai
description: Assistant Professor and Ramón y Cajal Researcher at Carlos III University of Madrid
taglong: Carlos III University of Madrid
tagshort: UC3M
url: https://icp.me
baseurl:  '/piazzai'
permalink: pretty
repo: https://github.com/piazzai/piazzai.github.io

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never
