# site settings

title:          cvless
tagline:        Jekyll theme for a beautiful online CV
url:            https://cvless.netlify.app
baseurl:        /
permalink:      pretty
repo:           https://github.com/username/username.github.io
version:        2.1.0

# author settings

author:
  name:         Place Holder
  email:        username@domain.com
photo:          /assets/photo.jpg

# build settings

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - .git
  - .jekyll-cache
  - .sass-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - vendor

sass:
  sass_dir:     _sass
  sourcemap:    never

feed:
  path:         atom.xml

autopages:
  enabled:      false

pagination:
  enabled:      true
  per_page:     1
  sort_reverse: true
  permalink:    /:num/
  title:        ":title &middot; Page :num"
